name: somnog-ems

services:
  postgres:
    image: postgres:16-alpine
    container_name: somnog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: somnog
      POSTGRES_PASSWORD: somnog
      POSTGRES_DB: emsdb
    ports:
      - '5533:5432' # Fixed internal port to 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-somnog}']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: somnog-rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672' # management UI, guest / guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: somnog-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: somnog-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # web inbox -> http://localhost:8025

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: